title: CalConnect Document Registry
author: CalConnect TC PUBLISH
email: tc-publish@calconnect.org
description: >-
  The CalConnect Document Registry
baseurl: ""
url: "https://www.calendarstandards.org"
twitter_username: calconnect
github_username:  CalConnect

markdown: kramdown
theme: jekyll-calconnect-theme
plugins:
  - jekyll-feed
  - jekyll/vite

collections:
  pages:
    output: true
    permalink: /:path/
  documents:
    output: true
    permalink: /:collection/:name/

defaults:
  - scope:
      path: ""
      type: "documents"
    values:
      layout: document

exclude:
  - README.adoc
  - Makefile
  - flake.*
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - "*.raw.rxl"
  - src-documents/
  - scripts/
  - config
  - vite.config.ts
  - package.json
  - package-lock.json

pagination:
  collection: 'posts'
  per_page: 30
  permalink: '/page/:num/'
  title: ':title - page :num'
  sort_field: 'date'
  sort_reverse: true
  category: 'posts'
  tag: ''
  locale: ''
  extension: html
  indexpage: 'index'
