#!/usr/bin/env bash

# Get all adoc paths of a certain :doctype: and :mn-document-class: in a
# directory
# (default: src-documents)
#

VERSION="0.0.1"

log() {
  printf "[$(date +'%Y-%m-%dT%H:%M:%S%z')]: %b\n" "$*"
} >&2

err() {
  printf "[$(date +'%Y-%m-%dT%H:%M:%S%z')]: \e[1;31mError:\e[m %b\n" "$*"
} >&2

ecdo() {
  log "Running: $*"
  "$@"
}

# BOOK KEEPING
DOC_TYPES="${DOC_TYPES:-}"
DOC_CLASS="${DOC_CLASS:-}"
FAILED_ADOCS=()
SUCCESS_ADOCS=()
ADOC_REFERENCES=()
COMMAND=

print-summary() {
  if [[ "${COMMAND:-}" = flags ]]
  then
    return
  fi

  if [[ -z "${DOC_TYPES}" || -z "${DOC_CLASS}" ]]
  then
    show_usage
    return
  fi

  local readable_docs=$(( ${#ADOC_REFERENCES[@]} - ${#FAILED_ADOCS[@]} ))

  log "There are \e[1m${#ADOC_REFERENCES[@]}\e[m documents in total."
  log "Successfully picked \e[1m${#SUCCESS_ADOCS[@]}\e[m out of \e[1m${readable_docs}\e[m readable documents that are of :mn-document-class: \e[1m${DOC_CLASS}\e[m and :doctype: \e[1m${DOC_TYPES}\e[m."
  if [[ "${#FAILED_ADOCS[@]}" -gt 0 ]]
  then
    err "Failed to process \e[1m${#FAILED_ADOCS[@]}\e[m documents:"
    for failure in "${FAILED_ADOCS[@]}"
    do
      err "  ${failure}"
    done
  fi
}

trap print-summary EXIT

METANORMA_YAML_PATHS=()

get-all-metanorma-yaml-paths() {
  local src_dir="${1:?Missing source directory}"

  while read -r yml
  do
    METANORMA_YAML_PATHS+=("$yml")
  done < <(find "$src_dir" -type f -name 'metanorma.y*ml')

  log "Found ${#METANORMA_YAML_PATHS[@]} metanorma YAML files"
}

get-all-sources-from-metanorma-yaml() {
  local yml="${1:?Missing metanorma YAML file}"
  local path_prefix="${yml%/*}"

  # log "pathPrefix is $pathPrefix"
  # Only proceed if 'files' is not null (should be an array)
  <"$yml" yq -r ".metanorma.source.files | select(null != .) | map(\"${path_prefix}/\" + .)"

}

get-all-sources-from-metanorma-yamls() {
  for yml in "${METANORMA_YAML_PATHS[@]}"
  do
    get-all-sources-from-metanorma-yaml "$yml"
  done
}

# Only search within the first n lines of the document
DOC_SEARCH_FIRST_N_LINES="${DOC_SEARCH_FIRST_N_LINES:-100}"

COMMON_DOC_TYPES=(
  standard
  directive
  guide
  specification
  report
  amendment
  technical-corrigendum
  administrative
  international-standard
  internet-draft
  advisory
)

# See: https://github.com/CalConnect/VCARD/blob/4d17cb269cbe48cff9603d293e1374bc81fba7f1/presentations/20180926-calconnect-mn-authoring/index.adoc?plain=1#L220

#   :doctype: can be standard, directive, guide, specification, report,
#   amendment, technical-corrigendum.
#
# But these are also seen in the wild:
#   administrative | international-standard | internet-draft | advisory
#
doc-is-of-doc-types() {
  local doc="${1:?Missing asciidoc path}"
  local doc_types="${2:?Missing doctype: standard | directive | guide | specification | report | amendment | technical-corrigendum | administrative | international-standard | internet-draft | advisory}"
  local doc_type

  for doc_type in $(echo "$doc_types" | tr ',' ' ')
  do
    if [[ -n "$doc_type" ]]
    then
      if <"$doc" \
        head -n "${DOC_SEARCH_FIRST_N_LINES}" \
        | grep -q ":doctype: $doc_type"
      then
        return 0
      fi
    fi
  done

  return 1
}

doc-is-of-doc-class() {
  local doc="${1:?Missing asciidoc path}"
  local doc_class="${2:?Missing mn-document-class}"

  <"$doc" \
    head -n "${DOC_SEARCH_FIRST_N_LINES}" \
    | grep -q ":mn-document-class: $doc_class"
}

doc-is-of-common-doc_types() {
  local doc="${1:?Missing asciidoc path}"

  for doc_type in "${COMMON_DOC_TYPES[@]}"
  do
    if doc-is-of-doc-types "$doc" "$doc_type"
    then
      return 0
    fi
  done

  local actual_doc_type
  actual_doc_type=$(
    <"$doc" head -n "${DOC_SEARCH_FIRST_N_LINES}" \
      | grep ":doctype:" \
      | cut -d' ' -f2-
  )

  err "Document $doc is not of any common doc types, got \`$actual_doc_type'."
  err "List of common doc types: ${COMMON_DOC_TYPES[*]}"

  return 1
}

# Paginated results are in separate arrays,
# so slurp them into one for a more uniform experience.
slurp-into-one-list() {
  command jq -s -r '[.[][]] | .[]'
}

# Filter out all the documents that are of a certain :mn-document-class:
# and a certain :doctype:.
filter-docs() {
  local doc

  for doc in "${ADOC_REFERENCES[@]}"
  do
    if [[ -r "${doc}" ]]
    then
      if filter-doc "$doc"
      then
        SUCCESS_ADOCS+=("$doc")
        echo "$doc"
      fi
    else
      err "Document $doc is not readable"
      FAILED_ADOCS+=("$doc")
    fi
  done
}



# If $DOC_CLASS is set, only include documents that are of that :mn-document-class:.
# If $DOC_TYPES is set, only include documents that are of that :doctype:.
filter-doc() {
  local doc="${1:?Missing asciidoc path}"

  if [[ -n "${DOC_CLASS}" ]] && \
    ! doc-is-of-doc-class "$doc" "${DOC_CLASS}"
  then
    return 1
  fi

  if [[ -n "${DOC_TYPES}" ]] && \
    ! doc-is-of-doc-types "$doc" "${DOC_TYPES}"
  then
    return 1
  fi

  return 0
}

# Bookkeeping
record-adoc-references() {
  while read -r line
  do
    ADOC_REFERENCES+=("$line")
  done < <( get-all-sources-from-metanorma-yamls \
    | slurp-into-one-list
  )
}

show_usage() {
  COMMAND=flags

  local prog_name="\e[1m${0}\e[22m"
  printf "%b" "Usage: $prog_name [subdir]
       $prog_name [-h|--help]
       $prog_name --version

  Return all adoc paths of a certain \e[4m:doctype:\e[24m and \e[4m:mn-document-class:\e[24m
  in a directory, as a list of newline-separated paths.

\e[4mFlags:\e[24m
  --version   Print the version and exit
  --help      Print this help message and exit

\e[4mParameters:\e[24m
  subdir      The directory to search for metanorma YAML files
              (default: src-documents)

\e[4mMandatory environment variables:\e[24m
  DOC_TYPES   The \e[4m:doctype:\e[24m to filter by.  Multiple DOC_TYPEs can
              be specified by separating them with a comma.
  DOC_CLASS   The \e[4m:mn-document-class:\e[24m to filter by

"

}

main() {
  if [[ "$1" == "-h" || "$1" == "--help" ]]
  then
    show_usage
    exit 0
  elif [[ "$1" == "--version" ]]
  then
    COMMAND=flags
    echo "${0} v${VERSION}"
    exit 0
  fi

  local subdir="${1:-src-documents}"

  DOC_TYPES="${DOC_TYPES-administrative}"
  DOC_CLASS="${DOC_CLASS-cc}"

  if [[ ! -d "${subdir}" ]]
  then
    err "Directory ${subdir} does not exist"
    exit 1
  fi

  if [[ -z "${DOC_TYPES:-}" ]]
  then
    err "DOC_TYPES is not set"
    exit 1
  fi

  if [[ -z "${DOC_CLASS:-}" ]]
  then
    err "DOC_CLASS is not set"
    exit 1
  fi

  get-all-metanorma-yaml-paths "${subdir:?Missing doc subdir}"
  record-adoc-references
  filter-docs
}

main "$@"
