#!/usr/bin/env ruby
# frozen_string_literal: true

# See: https://github.com/actions/runner/blob/deprecated_master/src/Misc/expressionFunc/hashFiles/src/hashFiles.ts

VERSION = '0.0.1'

require 'digest'

def debug(*args)
  return if (ENV['DEBUG'] || '').empty?

  $stderr.printf("\e[2mdebug:\e[1m %s\e[m\n", args.map(&:to_s).join(' '))
end

def err(*args)
  $stderr.printf("\e[1;31mError:\e[m %s\n", args.map(&:to_s).join(' '))
end

def warning(*args)
  $stderr.printf("\e[1;38:5:208mWarning:\e[m %s\n", args.map(&:to_s).join(' '))
end

def print_usage
  prog_name = "\e[1m#{$PROGRAM_NAME}\e[22m"
  warn <<~USAGE
    Usage: #{prog_name} FILE_OR_DIR...
           #{prog_name} [-h|--help]
           #{prog_name} --version

      Hash files and directories using SHA256.

    \e[4mFlags:\e[24m
      --version  Print the version and exit
      --help     Print this help message and exit

    \e[4mArguments:\e[24m
      FILE_OR_DIR  The file or directory to hash

    \e[4mEnvironment:\e[24m
      DEBUG       Enable debug output

  USAGE
end

def main(*args)
  if args.empty?
    print_usage
    exit 1
  else
    case args[0]
    when '--version'
      puts "#{$PROGRAM_NAME} v#{VERSION}"
      exit 0
    when '--help', '-h'
      print_usage
      exit 0
    end
  end
  hash_files(*args)
end

def sum(*arg)
  h = Digest::SHA256.new
  arg.each do |a|
    h.update(File.read(a))
  end
  h.hexdigest
end

# List all files within a directory, recursively
def find(dir)
  Dir.glob("#{dir}/**/*").select { |f| File.file?(f) }
end

def hash_files(*args)
  result = Digest::SHA256.new
  hashed_dirs = 0
  hashed_files = 0

  args.each do |dir_or_file|
    if File.directory?(dir_or_file)
      debug "Hashing #{dir_or_file} (dir)"
      find(dir_or_file).each do |fd|
        debug "Hashing #{fd} (file under dir: #{dir_or_file})"
        hashed_files += 1
        result.update(sum(fd))
      end

      hashed_dirs += 1
    elsif File.file?(dir_or_file)
      debug "Hashing #{dir_or_file} (file)"
      hashed_files += 1

      result.update(sum(dir_or_file))
    else
      debug "Hashing #{dir_or_file} (not found)"
      # Missing file not a fatal error
      warning "#{dir_or_file} not found.  Skipping."
    end
  end

  debug "Hash: #{result.hexdigest} (args: #{args.join(' ')})"
  debug "Hash summary: Files: #{hashed_files}, Dirs: #{hashed_dirs}"
  puts result.hexdigest
end

main(*ARGV)
