name: build_deploy

on:
  push:
    branches: [ main ]
  pull_request:
  repository_dispatch:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    name: Build site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
      - run: npm ci

      - name: Use Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: 3.3

      - name: Fetch released documents
        run: bundle exec rake releases:fetch

      - name: Build Relaton index
        run: bundle exec rake relaton:build

      - name: Build Jekyll site
        run: bundle exec rake jekyll

      - name: Debug
        if: ${{ github.ref != 'refs/heads/main' }}
        run: |
          ls -al _site
          ls _site/cc | head -20
          ls _site/relaton

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
